# Generated by Django 5.0.3 on 2024-06-06 00:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drugs', '0001_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiseaseRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Created At')),
                ('modified_at', models.DateField(auto_now=True, verbose_name='Modified At')),
                ('next_intake', models.CharField(blank=True, max_length=100, verbose_name='Next Intake')),
                ('prescription_cost', models.IntegerField(blank=True, null=True, verbose_name='Prescription Cost')),
                ('patient_claimed_cost', models.IntegerField(blank=True, null=True, verbose_name='Patient Claimed Cost')),
                ('pharmacy', models.CharField(blank=True, max_length=255, verbose_name='Pharmacy')),
                ('recipient', models.CharField(blank=True, max_length=100, verbose_name='Recipient')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('patient_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patientcase', verbose_name='Patient Case')),
            ],
            options={
                'verbose_name': 'Disease Record',
                'verbose_name_plural': 'Disease Records',
            },
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Created At')),
                ('modified_at', models.DateField(auto_now=True, verbose_name='Modified At')),
                ('diagnosis', models.TextField(blank=True, verbose_name='Diagnosis')),
                ('diagnosis_tests', models.TextField(blank=True, verbose_name='Diagnosis Tests')),
                ('drug_history', models.TextField(blank=True, verbose_name='Drug History')),
                ('surgery_history', models.TextField(blank=True, verbose_name='Surgery History')),
                ('other_diseases', models.TextField(blank=True, verbose_name='Other Diseases')),
                ('dietary_habits', models.TextField(blank=True, verbose_name='Dietary Habits')),
                ('movement_ability', models.CharField(blank=True, max_length=255, verbose_name='Movement Ability')),
                ('routines_ability', models.CharField(blank=True, max_length=255, verbose_name='Routines Ability')),
                ('talking_and_swallowing', models.CharField(blank=True, max_length=255, verbose_name='Talking and Swallowing')),
                ('gatherings_attending', models.CharField(blank=True, max_length=255, verbose_name='Gatherings Attending')),
                ('family_and_social', models.CharField(blank=True, max_length=255, verbose_name='Family and Social')),
                ('height', models.FloatField(blank=True, null=True, verbose_name='Height')),
                ('weight', models.FloatField(blank=True, null=True, verbose_name='Weight')),
                ('drugs_abuse', models.CharField(blank=True, max_length=255, verbose_name='Drugs Abuse')),
                ('other_information', models.CharField(blank=True, max_length=255, verbose_name='Other Information')),
                ('treatment_facilities', models.CharField(blank=True, max_length=255, verbose_name='Treatment Facilities')),
                ('doctors_names', models.CharField(blank=True, max_length=255, verbose_name='Doctors Names')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('patient_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patientcase', verbose_name='Patient Case')),
            ],
            options={
                'verbose_name': 'Medical Record',
                'verbose_name_plural': 'Medical Records',
            },
        ),
        migrations.CreateModel(
            name='PatientDisease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Created At')),
                ('modified_at', models.DateField(auto_now=True, verbose_name='Modified At')),
                ('disease_type', models.CharField(choices=[('infectious_and_parasitic', 'عفونی و انگلی'), ('cancer_and_blood_diseases', 'سرطان و بیماری های خونی'), ('safety_system', 'سیستم ایمنی'), ('glands', 'غدد'), ('psychiatry', 'اعصاب و روان'), ('neurology', 'مغز و اعصاب'), ('eye_disease', 'بیماری چشمی'), ('ear_nose_throat', 'گوش و حلق و بینی'), ('cardiovascular', 'قلبی-عروقی'), ('respiratory', 'تنفسی'), ('digestive', 'گوارشی'), ('skin', 'پوستی'), ('susculoskeletal', 'عضلانی-اسکلتی'), ('kidney_genitourinary_tract', 'کلیه و مجاری ادراری-تناسلی'), ('gynecology', 'زنان و زایمان\xa0'), ('genetic', 'ژنتیکی و مادرزادی\xa0'), ('accidents', 'سوانح'), ('other', 'سایر')], max_length=30, verbose_name='Disease Type')),
                ('disease_name', models.CharField(max_length=255, verbose_name='Disease Name')),
                ('diagnosis_year', models.IntegerField(verbose_name='Diagnosis Year')),
                ('status', models.CharField(choices=[('in_progress', 'Treatment In Progress'), ('stopped', 'Treatment Stopped'), ('cured', 'Cured')], max_length=20, verbose_name='Status')),
                ('disease_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medical_records.diseaserecord', verbose_name='Disease Record')),
            ],
            options={
                'verbose_name': 'Patient Disease',
                'verbose_name_plural': 'Patient Diseases',
            },
        ),
        migrations.CreateModel(
            name='PatientDoctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Created At')),
                ('modified_at', models.DateField(auto_now=True, verbose_name='Modified At')),
                ('doctor_name', models.CharField(blank=True, max_length=255, verbose_name='Doctor Name')),
                ('treatment_facilities', models.CharField(blank=True, max_length=255, verbose_name='Treatment Facilities')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], max_length=20, verbose_name='Status')),
                ('disease_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medical_records.diseaserecord', verbose_name='Disease Record')),
            ],
            options={
                'verbose_name': 'Patient Doctor',
                'verbose_name_plural': 'Patient Doctors',
            },
        ),
        migrations.CreateModel(
            name='PatientDrugRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Created At')),
                ('modified_at', models.DateField(auto_now=True, verbose_name='Modified At')),
                ('usage_start', models.CharField(max_length=30, verbose_name='Usage Start')),
                ('usage_duration', models.CharField(max_length=30, verbose_name='Usage Duration')),
                ('usage_instruction', models.CharField(max_length=30, verbose_name='Usage Instruction')),
                ('costs', models.IntegerField(blank=True, null=True, verbose_name='Costs')),
                ('costs_without_insurance', models.IntegerField(blank=True, null=True, verbose_name='Costs Without Insurance')),
                ('list_status', models.CharField(choices=[('single_prescription', 'Single Prescription'), ('without_insurance', 'Without Insurance'), ('other', 'Other')], max_length=20, verbose_name='List Status')),
                ('help_needed', models.BooleanField(verbose_name='Help Needed')),
                ('intake_intervals', models.CharField(max_length=100, verbose_name='Intake Intervals')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], max_length=20, verbose_name='Status')),
                ('disease_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medical_records.diseaserecord', verbose_name='Disease Record')),
                ('drug_brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drugs.drugbrand', verbose_name='Drug Brand')),
                ('generic_drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drugs.genericdrug', verbose_name='Generic Drug')),
            ],
            options={
                'verbose_name': 'Patient Drug Record',
                'verbose_name_plural': 'Patient Drug',
            },
        ),
        migrations.CreateModel(
            name='RelativeDisease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Created At')),
                ('modified_at', models.DateField(auto_now=True, verbose_name='Modified At')),
                ('relation', models.CharField(max_length=255, verbose_name='Relation')),
                ('disease_name', models.CharField(max_length=255, verbose_name='Disease Name')),
                ('infection_age', models.IntegerField(verbose_name='Infection Age')),
                ('current_health_status', models.CharField(max_length=255, verbose_name='Current Health Status')),
                ('medical_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medical_records.medicalrecord', verbose_name='Medical Record')),
            ],
            options={
                'verbose_name': 'Relative Disease',
                'verbose_name_plural': 'Relative Diseases',
            },
        ),
    ]
