# Generated by Django 5.0.3 on 2024-07-06 10:09

import django.db.models.deletion
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0001_initial'),
        ('patients', '0004_remove_othersupporter_other_information_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientdoctor',
            name='disease_record',
        ),
        migrations.RemoveField(
            model_name='patientdrugrecord',
            name='disease_record',
        ),
        migrations.RemoveField(
            model_name='patientdisease',
            name='disease_record',
        ),
        migrations.CreateModel(
            name='PatientChart',
            fields=[
            ],
            options={
                'verbose_name': 'Patient Chart',
                'verbose_name_plural': 'Patient Charts',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('patients.patientcase',),
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='other_diseases',
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='treatment_facilities',
        ),
        migrations.RemoveField(
            model_name='patientdoctor',
            name='treatment_facilities',
        ),
        migrations.RemoveField(
            model_name='patientdrugrecord',
            name='costs',
        ),
        migrations.RemoveField(
            model_name='patientdrugrecord',
            name='costs_without_insurance',
        ),
        migrations.AddField(
            model_name='patientdisease',
            name='patient_case',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='patients.patientcase', verbose_name='Patient Case'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patientdoctor',
            name='center_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Center Name'),
        ),
        migrations.AddField(
            model_name='patientdoctor',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='patientdoctor',
            name='patient_case',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='patients.patientcase', verbose_name='Patient Case'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patientdrugrecord',
            name='patient_case',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='patients.patientcase', verbose_name='Patient Case'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patientdrugrecord',
            name='patient_share',
            field=models.IntegerField(default=1, verbose_name='Patient Share'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patientdrugrecord',
            name='prescription_number',
            field=models.IntegerField(default=1, verbose_name='Prescription Number'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patientdrugrecord',
            name='price_difference',
            field=models.IntegerField(default=1, verbose_name='Price Difference'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patientdrugrecord',
            name='unit_price',
            field=models.IntegerField(default=1, verbose_name='Unit Price'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='patient_case',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='patients.patientcase', verbose_name='Patient Case'),
        ),
        migrations.AlterField(
            model_name='patientdrugrecord',
            name='intake_intervals',
            field=models.CharField(choices=[('two_weeks', 'Two Weeks'), ('three_weeks', 'Three Weeks'), ('monthly', 'Monthly'), ('two_months', 'Two_Months'), ('three_months', 'Three_Months'), ('six_months', 'Six_Months')], max_length=20, verbose_name='Intake Intervals'),
        ),
        migrations.AlterField(
            model_name='patientdrugrecord',
            name='usage_instruction',
            field=models.TextField(verbose_name='Usage Instruction'),
        ),
        migrations.AlterField(
            model_name='patientdrugrecord',
            name='usage_start',
            field=django_jalali.db.models.jDateField(verbose_name='Usage Start'),
        ),
        migrations.CreateModel(
            name='CurrentPatientState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_at', models.DateField(auto_now=True, verbose_name='Modified At')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Created At')),
                ('patient_state', models.TextField(verbose_name='Patient State')),
                ('current_symptom', models.TextField(verbose_name='Current Symptom')),
                ('main_treatment_process', models.TextField(verbose_name='Main Treatment Process')),
                ('other_description', models.TextField(verbose_name='Other Description')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('patient_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patientcase', verbose_name='Patient Case')),
            ],
            options={
                'verbose_name': 'Current Patient State',
                'verbose_name_plural': 'Current Patient States',
            },
        ),
        migrations.CreateModel(
            name='TreatmentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_at', models.DateField(auto_now=True, verbose_name='Modified At')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Created At')),
                ('treatment_follow', models.TextField(verbose_name='Treatment Follow')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], max_length=20, verbose_name='Status')),
                ('patient_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patientcase', verbose_name='Patient Case')),
                ('pharmacist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Pharmacist')),
            ],
            options={
                'verbose_name': 'Treatment Plan',
                'verbose_name_plural': 'Treatment Plans',
            },
        ),
        migrations.DeleteModel(
            name='DiseaseRecord',
        ),
        migrations.CreateModel(
            name='DiseaseRecord',
            fields=[
            ],
            options={
                'verbose_name': 'Disease Record',
                'verbose_name_plural': 'Disease Records',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('patients.patientcase',),
        ),
    ]
