# Generated by Django 5.0.3 on 2024-07-08 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0002_remove_patientdoctor_disease_record_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentpatientstate',
            name='other_description',
            field=models.TextField(blank=True, verbose_name='Other Description'),
        ),
        migrations.AlterField(
            model_name='currentpatientstate',
            name='patient_state',
            field=models.TextField(blank=True, verbose_name='Patient State'),
        ),
        migrations.AlterField(
            model_name='patientdisease',
            name='diagnosis_year',
            field=models.PositiveIntegerField(verbose_name='Diagnosis Year'),
        ),
        migrations.AlterField(
            model_name='patientdoctor',
            name='center_name',
            field=models.CharField(max_length=255, verbose_name='Center Name'),
        ),
        migrations.AlterField(
            model_name='patientdoctor',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='patientdoctor',
            name='doctor_name',
            field=models.CharField(max_length=255, verbose_name='Doctor Name'),
        ),
        migrations.AlterField(
            model_name='patientdrugrecord',
            name='patient_share',
            field=models.PositiveIntegerField(verbose_name='Patient Share'),
        ),
        migrations.AlterField(
            model_name='patientdrugrecord',
            name='prescription_number',
            field=models.PositiveIntegerField(verbose_name='Prescription Number'),
        ),
        migrations.AlterField(
            model_name='patientdrugrecord',
            name='price_difference',
            field=models.PositiveIntegerField(verbose_name='Price Difference'),
        ),
        migrations.AlterField(
            model_name='patientdrugrecord',
            name='unit_price',
            field=models.PositiveIntegerField(verbose_name='Unit Price'),
        ),
        migrations.AlterField(
            model_name='relativedisease',
            name='infection_age',
            field=models.PositiveIntegerField(verbose_name='Infection Age'),
        ),
        migrations.AlterField(
            model_name='relativedisease',
            name='relation',
            field=models.CharField(blank=True, max_length=255, verbose_name='Relation'),
        ),
    ]
