# Generated by Django 4.2.7 on 2023-11-24 21:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_at', django_jalali.db.models.jDateField(auto_now_add=True)),
                ('modified_at', django_jalali.db.models.jDateField(auto_now=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('birthdate', django_jalali.db.models.jDateField()),
                ('national_code', models.CharField(max_length=10)),
                ('nationality', models.CharField(choices=[('iranian', 'Iranian'), ('other', 'Other')], max_length=10)),
                ('first_guardian_name', models.CharField(max_length=255)),
                ('first_guardian_national_code', models.CharField(blank=True, max_length=10)),
                ('first_guardian_relation', models.CharField(max_length=255)),
                ('second_guardian_name', models.CharField(blank=True, max_length=255)),
                ('second_guardian_national_code', models.CharField(blank=True, max_length=10)),
                ('second_guardian_relation', models.CharField(blank=True, max_length=255)),
                ('social_insurance_type', models.CharField(choices=[('health_insurance', 'Health Insurance'), ('social_security', 'Social Security'), ('unemployment_insurance', 'Unemployment Insurance'), ('retirement_pension', 'Retirement Pension'), ('none', 'None')], max_length=255)),
                ('social_insurance_number', models.CharField(blank=True, max_length=255)),
                ('social_insurance_description', models.TextField(blank=True)),
                ('educational_status', models.CharField(choices=[('elementary', 'ابتدایی'), ('middle_school', 'سیکل'), ('high_school_diploma', 'دیپلم'), ('associate_degree', 'فوق دیپلم'), ('bachelors_degree', 'کارشناسی'), ('masters_degree', 'کارشناسی ارشد'), ('doctorate', 'دکتری'), ('none', 'ندارد')], max_length=20)),
                ('has_private_insurance', models.BooleanField()),
                ('private_insurance_name', models.TextField(null=True)),
                ('private_insurance_number', models.CharField(blank=True, max_length=255)),
                ('marital_status', models.CharField(choices=[('single', 'Single'), ('married', 'Married'), ('divorced', 'Divorced'), ('widowed', 'Widowed')], max_length=10)),
                ('marital_status_description', models.TextField(null=True)),
                ('housing_status', models.CharField(choices=[('owner', 'مالک'), ('rental', 'استیجاری- اجاره'), ('mortgaged', 'استیجاری - رهن'), ('mortgaged_rental', 'استیجاری - رهن و اجاره'), ('endowment', 'اوقاف'), ('relatives', 'بستگان')], max_length=20)),
                ('deposit_amount', models.IntegerField(null=True)),
                ('rent_amount', models.IntegerField(null=True)),
                ('has_job', models.BooleanField(null=True)),
                ('monthly_income', models.IntegerField()),
                ('subsidy', models.IntegerField()),
                ('family_monthly_expenses', models.IntegerField()),
                ('amount_of_installment_or_debt', models.IntegerField()),
                ('repayment_due_date', django_jalali.db.models.jDateField()),
                ('income_expenses_description', models.TextField()),
                ('province_of_residence', models.CharField(blank=True, choices=[('alborz', 'Alborz'), ('ardabil', 'Ardabil'), ('bushehr', 'Bushehr'), ('chaharmahal_and_bakhtiari', 'Chaharmahal and Bakhtiari'), ('east_azerbaijan', 'East Azerbaijan'), ('isfahan', 'Isfahan'), ('fars', 'Fars'), ('gilan', 'Gilan'), ('golestan', 'Golestan'), ('hamadan', 'Hamadan'), ('hormozgan', 'Hormozgan'), ('ilam', 'Ilam'), ('kerman', 'Kerman'), ('kermanshah', 'Kermanshah'), ('khuzestan', 'Khuzestan'), ('kohgiluyeh_and_boyer_ahmad', 'Kohgiluyeh and Boyer-Ahmad'), ('kurdistan', 'Kurdistan'), ('lorestan', 'Lorestan'), ('markazi', 'Markazi'), ('mazandaran', 'Mazandaran'), ('north_khorasan', 'North Khorasan'), ('qazvin', 'Qazvin'), ('qom', 'Qom'), ('razavi_khorasan', 'Razavi Khorasan'), ('semnan', 'Semnan'), ('sistan_and_baluchestan', 'Sistan and Baluchestan'), ('south_khorasan', 'South Khorasan'), ('tehran', 'Tehran'), ('west_azerbaijan', 'West Azerbaijan'), ('yazd', 'Yazd'), ('zanjan', 'Zanjan'), ('not_iranian', 'Not Iranian')], max_length=30)),
                ('city_of_residence', models.CharField(blank=True, max_length=255)),
                ('address', models.TextField(blank=True)),
                ('mobile_number', models.CharField(max_length=20)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('representor', models.CharField(max_length=255)),
                ('representor_relation', models.CharField(max_length=255)),
                ('referrer_name', models.CharField(max_length=255)),
                ('other_information', models.TextField(blank=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Relatives',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', django_jalali.db.models.jDateField(auto_now_add=True)),
                ('modified_at', django_jalali.db.models.jDateField(auto_now=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('relation', models.CharField(max_length=255)),
                ('year_of_birth', models.IntegerField()),
                ('marital_status', models.CharField(choices=[('single', 'Single'), ('married', 'Married'), ('divorced', 'Divorced'), ('widowed', 'Widowed')], max_length=10)),
                ('occupation', models.CharField(max_length=255)),
                ('monthly_income', models.IntegerField()),
                ('health_status', models.CharField(max_length=255)),
                ('patient_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.patientcase')),
            ],
        ),
        migrations.CreateModel(
            name='OtherSupporters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', django_jalali.db.models.jDateField(auto_now_add=True)),
                ('modified_at', django_jalali.db.models.jDateField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('support_amount', models.IntegerField()),
                ('support_start', django_jalali.db.models.jDateField()),
                ('support_end', django_jalali.db.models.jDateField()),
                ('other_information', models.TextField(blank=True)),
                ('patient_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.patientcase')),
            ],
        ),
    ]
