# Generated by Django 4.2.7 on 2023-11-24 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OtherSupporters',
            new_name='OtherSupporter',
        ),
        migrations.RenameModel(
            old_name='Relatives',
            new_name='Relative',
        ),
    ]
