# Generated by Django 5.0.3 on 2024-04-12 11:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_patientcase_deposit_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='othersupporter',
            options={'verbose_name': 'Other Supporter', 'verbose_name_plural': 'Other Supporters'},
        ),
        migrations.AlterModelOptions(
            name='patientcase',
            options={'verbose_name': 'Patient Case', 'verbose_name_plural': 'Patient Cases'},
        ),
        migrations.AlterModelOptions(
            name='relative',
            options={'verbose_name': 'Relative', 'verbose_name_plural': 'Relatives'},
        ),
        migrations.AlterField(
            model_name='othersupporter',
            name='created_at',
            field=models.DateField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='othersupporter',
            name='modified_at',
            field=models.DateField(auto_now=True, verbose_name='Modified At'),
        ),
        migrations.AlterField(
            model_name='othersupporter',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='othersupporter',
            name='other_information',
            field=models.TextField(blank=True, verbose_name='Other Information'),
        ),
        migrations.AlterField(
            model_name='othersupporter',
            name='patient_case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.patientcase', verbose_name='Patient Case'),
        ),
        migrations.AlterField(
            model_name='othersupporter',
            name='support_amount',
            field=models.IntegerField(verbose_name='Support Amount'),
        ),
        migrations.AlterField(
            model_name='othersupporter',
            name='support_end',
            field=models.DateField(verbose_name='Support End'),
        ),
        migrations.AlterField(
            model_name='othersupporter',
            name='support_start',
            field=models.DateField(verbose_name='Support Start'),
        ),
        migrations.AlterField(
            model_name='patientcase',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='patientcase',
            name='address',
            field=models.TextField(blank=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='patientcase',
            name='amount_of_installment_or_debt',
            field=models.IntegerField(verbose_name='Amount of Installment or Debt'),
        ),
        migrations.AlterField(
            model_name='patientcase',
            name='birthdate',
            field=models.DateField(verbose_name='Birthdate'),
        ),
        migrations.AlterField(
            model_name='patientcase',
            name='city_of_residence',
            field=models.CharField(blank=True, max_length=255, verbose_name='City of Residence'),
        ),
        migrations.AlterField(
            model_name='patientcase',
            name='created_at',
            field=models.DateField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='patientcase',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Creator'),
        ),
        migrations.AlterField(
            model_name='patientcase',
            name='deposit_amount',
            field=models.IntegerField(blank=True, verbose_name='Deposit Amount'),
        ),
        migrations.AlterField(
            model_name='patientcase',
            name='educational_status',
            field=models.CharField(choices=[('elementary', 'ابتدایی'), ('middle_school', 'سیکل'), ('high_school_diploma', 'دیپلم'), ('associate_degree', 'فوق دیپلم'), ('bachelors_degree', 'کارشناسی'), ('masters_degree', 'کارشناسی ارشد'), ('doctorate', 'دکتری'), ('none', 'ندارد')], max_length=20, verbose_name='Educational Status'),
        ),
        migrations.AlterField(
            model_name='patientcase',
            name='family_monthly_expenses',
            field=models.IntegerField(verbose_name='Family Monthly Expenses'),
        ),
        migrations.AlterField(
            model_name='patientcase',
            name='first_guardian_name',
            field=models.CharField(max_length=255, verbose_name='First Guardian Name'),
        ),
        migrations.AlterField(
            model_name='patientcase',
            name='first_guardian_national_code',
            field=models.CharField(blank=True, max_length=10, verbose_name='First Guardian National Code'),
        ),
        migrations.AlterField(
            model_name='patientcase',
            name='first_guardian_relation',
            field=models.CharField(max_length=255, verbose_name='First Guardian Relation'),
        ),
        migrations.AlterField(
            model_name='patientcase',
            name='first_name',
            field=models.CharField(max_length=255, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='patientcase',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='patientcase',
            name='has_job',
            field=models.BooleanField(null=True, verbose_name='Has Job'),
        ),
        migrations.AlterField(
            model_name='patientcase',
            name='has_private_insurance',
            field=models.BooleanField(verbose_name='Has Private Insurance'),
        ),
        migrations.AlterField(
            model_name='patientcase',
            name='housing_status',
            field=models.CharField(choices=[('owner', 'مالک'), ('rental', 'استیجاری- اجاره'), ('mortgaged', 'استیجاری - رهن'), ('mortgaged_rental', 'استیجاری - رهن و اجاره'), ('endowment', 'اوقاف'), ('relatives', 'بستگان')], max_length=20, verbose_name='Housing Status'),
        ),
        migrations.AlterField(
            model_name='patientcase',
            name='income_expenses_description',
            field=models.TextField(blank=True, verbose_name='Income Expenses Description'),
        ),
        migrations.AlterField(
            model_name='patientcase',
            name='last_name',
            field=models.CharField(max_length=255, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='patientcase',
            name='marital_status',
            field=models.CharField(choices=[('single', 'Single'), ('married', 'Married'), ('divorced', 'Divorced'), ('widowed', 'Widowed')], max_length=10, verbose_name='Marital Status'),
        ),
        migrations.AlterField(
            model_name='patientcase',
            name='marital_status_description',
            field=models.TextField(blank=True, verbose_name='Marital Status Description'),
        ),
        migrations.AlterField(
            model_name='patientcase',
            name='mobile_number',
            field=models.CharField(max_length=20, verbose_name='Mobile Number'),
        ),
        migrations.AlterField(
            model_name='patientcase',
            name='modified_at',
            field=models.DateField(auto_now=True, verbose_name='Modified At'),
        ),
        migrations.AlterField(
            model_name='patientcase',
            name='monthly_income',
            field=models.IntegerField(verbose_name='Monthly Income'),
        ),
        migrations.AlterField(
            model_name='patientcase',
            name='national_code',
            field=models.CharField(max_length=10, verbose_name='National Code'),
        ),
        migrations.AlterField(
            model_name='patientcase',
            name='nationality',
            field=models.CharField(choices=[('iranian', 'Iranian'), ('other', 'Other')], max_length=10, verbose_name='Nationality'),
        ),
        migrations.AlterField(
            model_name='patientcase',
            name='other_information',
            field=models.TextField(blank=True, verbose_name='Other Information'),
        ),
        migrations.AlterField(
            model_name='patientcase',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='patientcase',
            name='private_insurance_name',
            field=models.TextField(blank=True, verbose_name='Private Insurance Name'),
        ),
        migrations.AlterField(
            model_name='patientcase',
            name='private_insurance_number',
            field=models.CharField(blank=True, max_length=255, verbose_name='Private Insurance Number'),
        ),
        migrations.AlterField(
            model_name='patientcase',
            name='province_of_residence',
            field=models.CharField(blank=True, choices=[('alborz', 'Alborz'), ('ardabil', 'Ardabil'), ('bushehr', 'Bushehr'), ('chaharmahal_and_bakhtiari', 'Chaharmahal and Bakhtiari'), ('east_azerbaijan', 'East Azerbaijan'), ('isfahan', 'Isfahan'), ('fars', 'Fars'), ('gilan', 'Gilan'), ('golestan', 'Golestan'), ('hamadan', 'Hamadan'), ('hormozgan', 'Hormozgan'), ('ilam', 'Ilam'), ('kerman', 'Kerman'), ('kermanshah', 'Kermanshah'), ('khuzestan', 'Khuzestan'), ('kohgiluyeh_and_boyer_ahmad', 'Kohgiluyeh and Boyer-Ahmad'), ('kurdistan', 'Kurdistan'), ('lorestan', 'Lorestan'), ('markazi', 'Markazi'), ('mazandaran', 'Mazandaran'), ('north_khorasan', 'North Khorasan'), ('qazvin', 'Qazvin'), ('qom', 'Qom'), ('razavi_khorasan', 'Razavi Khorasan'), ('semnan', 'Semnan'), ('sistan_and_baluchestan', 'Sistan and Baluchestan'), ('south_khorasan', 'South Khorasan'), ('tehran', 'Tehran'), ('west_azerbaijan', 'West Azerbaijan'), ('yazd', 'Yazd'), ('zanjan', 'Zanjan'), ('not_iranian', 'Not Iranian')], max_length=30, verbose_name='Province of Residence'),
        ),
        migrations.AlterField(
            model_name='patientcase',
            name='referrer_name',
            field=models.CharField(max_length=255, verbose_name='Referrer Name'),
        ),
        migrations.AlterField(
            model_name='patientcase',
            name='rent_amount',
            field=models.IntegerField(blank=True, verbose_name='Rent Amount'),
        ),
        migrations.AlterField(
            model_name='patientcase',
            name='repayment_due_date',
            field=models.DateField(verbose_name='Repayment Due Date'),
        ),
        migrations.AlterField(
            model_name='patientcase',
            name='representor',
            field=models.CharField(max_length=255, verbose_name='Representor'),
        ),
        migrations.AlterField(
            model_name='patientcase',
            name='representor_relation',
            field=models.CharField(max_length=255, verbose_name='Representor Relation'),
        ),
        migrations.AlterField(
            model_name='patientcase',
            name='second_guardian_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Second Guardian Name'),
        ),
        migrations.AlterField(
            model_name='patientcase',
            name='second_guardian_national_code',
            field=models.CharField(blank=True, max_length=10, verbose_name='Second Guardian National Code'),
        ),
        migrations.AlterField(
            model_name='patientcase',
            name='second_guardian_relation',
            field=models.CharField(blank=True, max_length=255, verbose_name='Second Guardian Relation'),
        ),
        migrations.AlterField(
            model_name='patientcase',
            name='social_insurance_description',
            field=models.TextField(blank=True, verbose_name='Social Insurance Description'),
        ),
        migrations.AlterField(
            model_name='patientcase',
            name='social_insurance_number',
            field=models.CharField(blank=True, max_length=255, verbose_name='Social Insurance Number'),
        ),
        migrations.AlterField(
            model_name='patientcase',
            name='social_insurance_type',
            field=models.CharField(choices=[('health_insurance', 'Health Insurance'), ('social_security', 'Social Security'), ('unemployment_insurance', 'Unemployment Insurance'), ('retirement_pension', 'Retirement Pension'), ('none', 'None')], max_length=255, verbose_name='Social Insurance Type'),
        ),
        migrations.AlterField(
            model_name='patientcase',
            name='subsidy',
            field=models.IntegerField(verbose_name='Subsidy'),
        ),
        migrations.AlterField(
            model_name='relative',
            name='created_at',
            field=models.DateField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='relative',
            name='first_name',
            field=models.CharField(max_length=255, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='relative',
            name='health_status',
            field=models.CharField(max_length=255, verbose_name='Health Status'),
        ),
        migrations.AlterField(
            model_name='relative',
            name='last_name',
            field=models.CharField(max_length=255, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='relative',
            name='marital_status',
            field=models.CharField(choices=[('single', 'Single'), ('married', 'Married'), ('divorced', 'Divorced'), ('widowed', 'Widowed')], max_length=10, verbose_name='Marital Status'),
        ),
        migrations.AlterField(
            model_name='relative',
            name='modified_at',
            field=models.DateField(auto_now=True, verbose_name='Modified At'),
        ),
        migrations.AlterField(
            model_name='relative',
            name='monthly_income',
            field=models.IntegerField(verbose_name='Monthly Income'),
        ),
        migrations.AlterField(
            model_name='relative',
            name='occupation',
            field=models.CharField(max_length=255, verbose_name='Occupation'),
        ),
        migrations.AlterField(
            model_name='relative',
            name='patient_case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.patientcase', verbose_name='Patient Case'),
        ),
        migrations.AlterField(
            model_name='relative',
            name='relation',
            field=models.CharField(max_length=255, verbose_name='Relation'),
        ),
        migrations.AlterField(
            model_name='relative',
            name='year_of_birth',
            field=models.IntegerField(verbose_name='Year of Birth'),
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Created At')),
                ('modified_at', models.DateField(auto_now=True, verbose_name='Modified At')),
                ('type', models.CharField(choices=[('birth_certificate', 'شناسنامه'), ('id_card', 'کارت ملی'), ('guardian_id_card', 'کارت ملی سرپرست خانوار'), ('guardian_birth_certificate', 'شناسنامه سرپرست خانوار'), ('job_certificate', 'مدرک شغلی'), ('property_certificate', 'مدرک ملکی'), ('drugs_images', 'تصویر داروها'), ('supplementary_insurance', 'بیمه تکمیلی'), ('insurance_letter', 'معرفی\u200cنامه بیمه'), ('introduction_letter', 'معرفی\u200cنامه'), ('prescription', 'نسخه'), ('pre_invoice', 'پیش فاکتور'), ('case_sheet', 'برگه خلاصه پرونده'), ('doctor_note', 'گواهی پزشک'), ('lab_results', 'نتایج آزمایش\u200cها'), ('radiology', 'عکس\u200cبرداری'), ('statement', 'فرم اظهارنامه'), ('special_medicine_form', 'فرم داروهای تک\u200cنسخه\u200cای')], max_length=30, verbose_name='Type')),
                ('uploaded_file', models.FileField(upload_to='uploads/documents/', verbose_name='File')),
                ('patient_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.patientcase', verbose_name='Patient Case')),
            ],
        ),
    ]
