# Generated by Django 5.0.3 on 2024-04-12 16:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_document_options_patientcase_helper_comment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Created At')),
                ('modified_at', models.DateField(auto_now=True, verbose_name='Modified At')),
                ('disease_type', models.CharField(choices=[('Infectious and parasitic', 'عفونی و انگلی'), ('Cancer and blood diseases', 'سرطان و بیماری های خونی'), ('Safety system', 'سیستم ایمنی'), ('Glands', 'غدد'), ('Psychiatry', 'اعصاب و روان'), ('Neurology', 'مغز و اعصاب'), ('Eye disease', 'بیماری چشمی'), ('Ear nose and throat', 'گوش و حلق و بینی'), ('Cardiovascular', 'قلبی-عروقی'), ('Respiratory', 'تنفسی'), ('Digestive', 'گوارشی'), ('Skin', 'پوستی'), ('Musculoskeletal', 'عضلانی-اسکلتی'), ('Kidney and genitourinary tract', 'کلیه و مجاری ادراری-تناسلی'), ('Obstetrics and Gynecology', 'زنان و زایمان\xa0'), ('Genetic and congenital', 'ژنتیکی و مادرزادی\xa0'), ('Accidents', 'سوانح'), ('other', 'سایر')], max_length=30, verbose_name='Disease Type')),
                ('disease_name', models.CharField(max_length=255, verbose_name='Disease Name')),
                ('second_disease_name', models.CharField(blank=True, max_length=255, verbose_name='Disease Name (2nd)')),
                ('diagnosis_year', models.IntegerField(verbose_name='Diagnosis Year')),
                ('diagnosis', models.TextField(blank=True, verbose_name='Diagnosis')),
                ('diagnosis_tests', models.TextField(blank=True, verbose_name='Diagnosis Tests')),
                ('drug_history', models.TextField(blank=True, verbose_name='Drug History')),
                ('surgery_history', models.TextField(blank=True, verbose_name='Surgery History')),
                ('other_diseases', models.TextField(blank=True, verbose_name='Other Diseases')),
                ('dietary_habits', models.TextField(blank=True, verbose_name='Dietary Habits')),
                ('movement_ability', models.CharField(blank=True, max_length=255, verbose_name='Movement Ability')),
                ('routines_ability', models.CharField(blank=True, max_length=255, verbose_name='Routines Ability')),
                ('talking_and_swallowing', models.CharField(blank=True, max_length=255, verbose_name='Talking and Swallowing')),
                ('gatherings_attending', models.CharField(blank=True, max_length=255, verbose_name='Gatherings Attending')),
                ('family_and_social', models.CharField(blank=True, max_length=255, verbose_name='ّFamily and Social')),
                ('height', models.FloatField(blank=True, verbose_name='Height')),
                ('weight', models.FloatField(blank=True, verbose_name='Weight')),
                ('drugs_abuse', models.CharField(blank=True, max_length=255, verbose_name='Drugs Abuse')),
                ('other_information', models.CharField(blank=True, max_length=255, verbose_name='Other Information')),
                ('treatment_facilities', models.CharField(blank=True, max_length=255, verbose_name='Treatment Facilities')),
                ('doctors_names', models.CharField(blank=True, max_length=255, verbose_name='Doctors Names')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
                ('patient_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.patientcase', verbose_name='Patient Case')),
            ],
            options={
                'verbose_name': 'Medical Record',
                'verbose_name_plural': 'Medical Records',
            },
        ),
    ]
