# Generated by Django 5.0.3 on 2024-04-12 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_medicalrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalrecord',
            name='height',
            field=models.FloatField(blank=True, null=True, verbose_name='Height'),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='weight',
            field=models.FloatField(blank=True, null=True, verbose_name='Weight'),
        ),
    ]
