# Generated by Django 5.0.3 on 2024-04-23 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_medicalrecord_height_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientcase',
            name='deposit_amount',
            field=models.IntegerField(blank=True, null=True, verbose_name='Deposit Amount'),
        ),
        migrations.AlterField(
            model_name='patientcase',
            name='rent_amount',
            field=models.IntegerField(blank=True, null=True, verbose_name='Rent Amount'),
        ),
    ]
