# Generated by Django 5.0.3 on 2024-04-26 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_patientcase_deposit_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='uploaded_file',
            field=models.FileField(upload_to='documents/', verbose_name='File'),
        ),
    ]
