# Generated by Django 5.0.3 on 2024-05-03 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_document_uploaded_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrugBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=255, verbose_name='Brand Name')),
                ('country', models.CharField(max_length=30, verbose_name='Country')),
                ('address', models.CharField(max_length=255, verbose_name='Address')),
                ('phone', models.CharField(max_length=20, verbose_name='Phone')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Created At')),
                ('modified_at', models.DateField(auto_now=True, verbose_name='Modified At')),
            ],
            options={
                'verbose_name': 'Drug Brand',
                'verbose_name_plural': 'Drug Brands',
            },
        ),
        migrations.CreateModel(
            name='GenericDrug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Created At')),
                ('modified_at', models.DateField(auto_now=True, verbose_name='Modified At')),
            ],
            options={
                'verbose_name': 'Generic Drug',
                'verbose_name_plural': 'Generic Drugs',
            },
        ),
    ]
