# Generated by Django 5.0.3 on 2024-05-04 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_drugbrand_genericdrug'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientcase',
            name='father_name',
            field=models.CharField(default='aa', max_length=255, verbose_name='Father Name'),
            preserve_default=False,
        ),
    ]
