# Generated by Django 5.0.3 on 2024-05-09 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_patientdrug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientdrug',
            name='creator',
        ),
    ]
