# Generated by Django 5.0.3 on 2024-05-12 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_patientcase_father_name'),
        ('home', '0012_remove_patientdrug_creator'),
    ]

    operations = [
    ]
