# Generated by Django 5.0.3 on 2024-05-12 18:53

import django.db.models.deletion
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_merge_20240512_2223'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientcase',
            name='creator',
        ),
        migrations.AddField(
            model_name='patientcase',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='family_and_social',
            field=models.CharField(blank=True, max_length=255, verbose_name='Family and Social'),
        ),
        migrations.AlterField(
            model_name='patientcase',
            name='birthdate',
            field=django_jalali.db.models.jDateField(verbose_name='Birthdate'),
        ),
    ]
