# Generated by Django 5.0.3 on 2024-05-12 19:40

import django.db.models.deletion
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_remove_patientcase_creator_patientcase_created_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientcase',
            name='social_insurance_number',
        ),
        migrations.AddField(
            model_name='patientcase',
            name='case_completion_date',
            field=django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='Case Completion Date'),
        ),
        migrations.AddField(
            model_name='patientcase',
            name='case_number',
            field=models.CharField(blank=True, max_length=255, verbose_name='Case Number'),
        ),
        migrations.AddField(
            model_name='patientcase',
            name='guardian_status',
            field=models.CharField(choices=[('self', 'Self'), ('other', 'Other')], default='self', max_length=10, verbose_name='Guardian Status'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patientcase',
            name='job_description',
            field=models.TextField(blank=True, verbose_name='Job Description'),
        ),
        migrations.AddField(
            model_name='patientcase',
            name='refer_date',
            field=django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='Refer Date'),
        ),
        migrations.AlterField(
            model_name='othersupporter',
            name='support_end',
            field=django_jalali.db.models.jDateField(verbose_name='Support End'),
        ),
        migrations.AlterField(
            model_name='othersupporter',
            name='support_start',
            field=django_jalali.db.models.jDateField(verbose_name='Support Start'),
        ),
        migrations.AlterField(
            model_name='patientcase',
            name='created_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='patientcase',
            name='housing_status',
            field=models.CharField(choices=[('owner', 'مالک'), ('rental', 'استیجاری- اجاره'), ('mortgaged', 'استیجاری - رهن'), ('mortgaged_rental', 'استیجاری - رهن و اجاره'), ('endowment', 'اوقاف'), ('relatives', 'بستگان'), ('janitor', 'سرایدار'), ('other', 'Other')], max_length=20, verbose_name='Housing Status'),
        ),
        migrations.AlterField(
            model_name='patientcase',
            name='marital_status',
            field=models.CharField(choices=[('single', 'Single'), ('married', 'Married'), ('temp_married', 'Temp Married'), ('divorced', 'Divorced'), ('widowed', 'Widowed'), ('separated', 'Separated')], max_length=20, verbose_name='Marital Status'),
        ),
        migrations.AlterField(
            model_name='patientcase',
            name='repayment_due_date',
            field=django_jalali.db.models.jDateField(verbose_name='Repayment Due Date'),
        ),
        migrations.AlterField(
            model_name='patientcase',
            name='social_insurance_type',
            field=models.CharField(choices=[('health_insurance', 'Health Insurance'), ('social_security', 'Social Security'), ('medical_services', 'Medical Services'), ('armed_forces', 'Armed Forces'), ('other', 'Other'), ('none', 'None')], max_length=255, verbose_name='Social Insurance Type'),
        ),
        migrations.AlterField(
            model_name='relative',
            name='marital_status',
            field=models.CharField(choices=[('single', 'Single'), ('married', 'Married'), ('temp_married', 'Temp Married'), ('divorced', 'Divorced'), ('widowed', 'Widowed'), ('separated', 'Separated')], max_length=20, verbose_name='Marital Status'),
        ),
    ]
