# Generated by Django 5.0.3 on 2024-05-16 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_remove_medicalrecord_diagnosis_year_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientdisease',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='patientdoctor',
            name='created_by',
        ),
    ]
