# Generated by Django 5.0.3 on 2024-05-23 20:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_remove_medicalrecord_doctors_names_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patientdrugrecord',
            options={'verbose_name': 'Patient Drug Record', 'verbose_name_plural': 'Patient Drug'},
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='doctors_names',
            field=models.CharField(blank=True, max_length=255, verbose_name='Doctors Names'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='treatment_facilities',
            field=models.CharField(blank=True, max_length=255, verbose_name='Treatment Facilities'),
        ),
        migrations.CreateModel(
            name='Draft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Created At')),
                ('modified_at', models.DateField(auto_now=True, verbose_name='Modified At')),
                ('draft_type', models.CharField(choices=[('P', 'P'), ('IT', 'IT')], max_length=10, verbose_name='Draft Type')),
                ('status', models.CharField(choices=[('active', 'فعال'), ('inactive', 'غیرفعال'), ('pending', 'در انتظار')], max_length=30, verbose_name='Status')),
                ('draft_create_date', models.DateField(verbose_name='Draft Create Date')),
                ('draft_receive_date', models.DateField(verbose_name='Draft Receive Date')),
                ('drug_receive_date', models.DateField(verbose_name='Drug Receive Date')),
                ('invoice_create_date', models.DateField(verbose_name='Invoice Create Date')),
                ('payment_date', models.DateField(verbose_name='Payment Date')),
                ('invoice_amount', models.PositiveIntegerField(verbose_name='Invoice Amount')),
                ('cash_draft_amount', models.PositiveIntegerField(verbose_name='Cash Draft Amount')),
                ('drug_draft_amount', models.PositiveIntegerField(verbose_name='Drug Draft Amount')),
                ('patient_amount', models.PositiveIntegerField(verbose_name='Patient Amount')),
                ('insurance_amount', models.PositiveIntegerField(verbose_name='Insurance Amount')),
                ('supplier_type', models.CharField(choices=[('pharmacy', 'داروخانه'), ('factory', 'کارخانه')], max_length=10, verbose_name='Supplier Type')),
                ('supplier_name', models.CharField(default=None, max_length=255, verbose_name='Supplier Name')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
                ('patient_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.patientcase', verbose_name='Patient Case')),
            ],
            options={
                'verbose_name': 'Draft',
                'verbose_name_plural': 'Drafts',
            },
        ),
        migrations.CreateModel(
            name='DraftDrug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Created At')),
                ('modified_at', models.DateField(auto_now=True, verbose_name='Modified At')),
                ('count', models.PositiveIntegerField(verbose_name='Count')),
                ('draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.draft', verbose_name='Draft')),
                ('drug_brand', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='home.drugbrand', verbose_name='Drug Brand')),
                ('generic_drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.genericdrug', verbose_name='Generic Drug')),
            ],
            options={
                'verbose_name': 'Draft Drug',
                'verbose_name_plural': 'Draft Drugs',
            },
        ),
        migrations.CreateModel(
            name='DraftSupporter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Created At')),
                ('modified_at', models.DateField(auto_now=True, verbose_name='Modified At')),
                ('support_amount', models.PositiveIntegerField(verbose_name='Support Amount')),
                ('draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.draft', verbose_name='Draft')),
                ('supporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.othersupporter', verbose_name='Supporter')),
            ],
            options={
                'verbose_name': 'Draft Supporter',
                'verbose_name_plural': 'Draft Supporters',
            },
        ),
    ]
