# Generated by Django 5.0.3 on 2024-05-24 13:09

import django.db.models.deletion
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_alter_patientdrugrecord_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InputLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Created At')),
                ('modified_at', models.DateField(auto_now=True, verbose_name='Modified At')),
                ('first_name', models.CharField(max_length=255, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=255, verbose_name='Last Name')),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='Phone Number')),
                ('contact_location', models.CharField(max_length=100, verbose_name='Contact Location')),
                ('disease_type', models.CharField(choices=[('infectious_and_parasitic', 'عفونی و انگلی'), ('cancer_and_blood_diseases', 'سرطان و بیماری های خونی'), ('safety_system', 'سیستم ایمنی'), ('glands', 'غدد'), ('psychiatry', 'اعصاب و روان'), ('neurology', 'مغز و اعصاب'), ('eye_disease', 'بیماری چشمی'), ('ear_nose_throat', 'گوش و حلق و بینی'), ('cardiovascular', 'قلبی-عروقی'), ('respiratory', 'تنفسی'), ('digestive', 'گوارشی'), ('skin', 'پوستی'), ('susculoskeletal', 'عضلانی-اسکلتی'), ('kidney_genitourinary_tract', 'کلیه و مجاری ادراری-تناسلی'), ('gynecology', 'زنان و زایمان\xa0'), ('genetic', 'ژنتیکی و مادرزادی\xa0'), ('accidents', 'سوانح'), ('other', 'سایر')], max_length=30, verbose_name='Disease Type')),
                ('disease_name', models.CharField(max_length=255, verbose_name='Disease Name')),
                ('drugs_cost', models.IntegerField(verbose_name='Drugs Cost')),
                ('treatment_program', models.CharField(blank=True, max_length=100, verbose_name='Treatment Program')),
                ('province_of_residence', models.CharField(blank=True, choices=[('alborz', 'Alborz'), ('ardabil', 'Ardabil'), ('bushehr', 'Bushehr'), ('chaharmahal_and_bakhtiari', 'Chaharmahal and Bakhtiari'), ('east_azerbaijan', 'East Azerbaijan'), ('isfahan', 'Isfahan'), ('fars', 'Fars'), ('gilan', 'Gilan'), ('golestan', 'Golestan'), ('hamadan', 'Hamadan'), ('hormozgan', 'Hormozgan'), ('ilam', 'Ilam'), ('kerman', 'Kerman'), ('kermanshah', 'Kermanshah'), ('khuzestan', 'Khuzestan'), ('kohgiluyeh_and_boyer_ahmad', 'Kohgiluyeh and Boyer-Ahmad'), ('kurdistan', 'Kurdistan'), ('lorestan', 'Lorestan'), ('markazi', 'Markazi'), ('mazandaran', 'Mazandaran'), ('north_khorasan', 'North Khorasan'), ('qazvin', 'Qazvin'), ('qom', 'Qom'), ('razavi_khorasan', 'Razavi Khorasan'), ('semnan', 'Semnan'), ('sistan_and_baluchestan', 'Sistan and Baluchestan'), ('south_khorasan', 'South Khorasan'), ('tehran', 'Tehran'), ('west_azerbaijan', 'West Azerbaijan'), ('yazd', 'Yazd'), ('zanjan', 'Zanjan'), ('not_iranian', 'Not Iranian')], max_length=30, verbose_name='Province of Residence')),
                ('city_of_residence', models.CharField(blank=True, max_length=255, verbose_name='City of Residence')),
                ('referrer_name', models.CharField(blank=True, max_length=255, verbose_name='Referrer Name')),
                ('birthdate', django_jalali.db.models.jDateField(verbose_name='Birthdate')),
                ('contact_description', models.TextField(blank=True, verbose_name='Contact Description')),
                ('has_social_insurance', models.BooleanField(verbose_name='Has Social Insurance')),
                ('has_private_insurance', models.BooleanField(verbose_name='Has Private Insurance')),
                ('status', models.CharField(choices=[('reception', 'Reception'), ('waiting', 'Waiting')], max_length=30, verbose_name='Status')),
                ('last_action', models.TextField(blank=True, max_length=255, verbose_name='Last Action')),
                ('last_action_date', django_jalali.db.models.jDateField(blank=True, verbose_name='Last Action Date')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Input Log',
                'verbose_name_plural': 'Input Logs',
            },
        ),
    ]
