# Generated by Django 5.0.3 on 2024-05-24 13:17

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_alter_inputlog_birthdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputlog',
            name='birthdate',
            field=django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='Birthdate'),
        ),
        migrations.AlterField(
            model_name='inputlog',
            name='last_action_date',
            field=django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='Last Action Date'),
        ),
    ]
