# Generated by Django 5.0.3 on 2024-05-28 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_alter_inputlog_birthdate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientcase',
            name='active',
        ),
        migrations.AddField(
            model_name='patientcase',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('waiting', 'Waiting'), ('semi-active', 'Semi Active')], default='waiting', max_length=20, verbose_name='Status'),
            preserve_default=False,
        ),
    ]
