# Generated by Django 5.0.3 on 2024-07-10 18:26

import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_remove_diseaserecord_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inputlog',
            name='input_draft_status',
            field=models.CharField(choices=[('identified', 'شناسایی شده'), ('evaluated', 'ارزیابی شده'), ('accepted', 'پذیرش'), ('rejected', 'عدم پذیرش'), ('waiting', 'در انتظار')], default='waiting', max_length=30, verbose_name='Input Draft Status'),
        ),
        migrations.AlterField(
            model_name='inputlog',
            name='birthdate',
            field=django_jalali.db.models.jDateField(null=True, verbose_name='Birthdate'),
        ),
        migrations.AlterField(
            model_name='inputlog',
            name='contact_description',
            field=models.TextField(verbose_name='Contact Description'),
        ),
        migrations.AlterField(
            model_name='inputlog',
            name='last_action',
            field=models.CharField(choices=[('interview_appointment_set', 'تنظیم قرار مصاحبه'), ('file_created', 'تشکیل پرونده'), ('under_review', 'در حال بررسی'), ('referred', 'ارجاع'), ('waiting_foreign_single_dose', 'در انتظار- تک نسخه ای خارجی'), ('waiting_domestic_single_dose', 'در انتظار- تک نسخه ای داخلی'), ('waiting_expensive', 'در انتظار- گران قیمت'), ('waiting_foreign_nationals', 'در انتظار - اتباع'), ('no_response', 'عدم پاسخگویی'), ('patient_did_not_create_file', 'عدم مراجعه بیمار برای تشکیل پرونده'), ('resident_of_city', 'ساکن شهرستان'), ('covered_by_other_charities', 'پوشش سایر خیریه ها'), ('covered_by_basic_insurance', 'پوشش بیمه پایه'), ('covered_by_supplementary_insurance', 'پوشش بیمه تکمیلی'), ('no_drug_needed', 'عدم نیاز دارویی'), ('financial_aid_requested', 'درخواست کمک مالی'), ('treatment_completed', 'اتمام دوره درمان'), ('patient_unwilling_to_follow_up', 'عدم تمایل و پیگیری بیمار'), ('drug_equipment_requested', 'درخواست تجهیزات دارویی'), ('drug_regimen_changed', 'تغییر رژیم دارویی'), ('no_contract_pharmacy', 'عدم داروخانه طرف قرارداد'), ('deceased', 'فوت'), ('other', 'سایر')], max_length=255, verbose_name='Last Action'),
        ),
        migrations.AlterField(
            model_name='inputlog',
            name='last_action_date',
            field=django_jalali.db.models.jDateField(null=True, verbose_name='Last Action Date'),
        ),
    ]
