# Generated by Django 5.0.3 on 2024-05-28 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_remove_patientcase_active_patientcase_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientcase',
            name='private_insurance_number',
        ),
        migrations.AddField(
            model_name='patientcase',
            name='private_insurance_description',
            field=models.TextField(blank=True, verbose_name='Private Insurance Description'),
        ),
        migrations.AlterField(
            model_name='patientcase',
            name='private_insurance_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Private Insurance Name'),
        ),
    ]
