# Generated by Django 5.0.3 on 2024-07-06 10:09

import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_remove_diseaserecord_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inputlog',
            name='birthdate',
        ),
        migrations.RemoveField(
            model_name='inputlog',
            name='treatment_program',
        ),
        migrations.AddField(
            model_name='inputlog',
            name='age',
            field=models.PositiveIntegerField(default=1, verbose_name='Age'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inputlog',
            name='service_date',
            field=django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='Service Date'),
        ),
        migrations.AlterField(
            model_name='inputlog',
            name='contact_location',
            field=models.CharField(choices=[('office_call', 'Office Call'), ('novatel_call', 'Novatel Call'), ('13_aban_office', '13 Aban Office'), ('university_office', 'University Office'), ('yazd_office', 'Yazd Office'), ('prescription_approval_office', 'Prescription Approval Office')], max_length=50, verbose_name='Contact Location'),
        ),
        migrations.AlterField(
            model_name='inputlog',
            name='phone_number',
            field=models.CharField(max_length=20, unique=True, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='inputlog',
            name='status',
            field=models.CharField(choices=[('reception', 'Reception'), ('waiting', 'Waiting'), ('rejection', 'Rejection'), ('detected', 'Detected'), ('reviewed', 'Reviewed')], max_length=30, verbose_name='Status'),
        ),
    ]
