# Generated by Django 5.0.3 on 2024-07-08 12:41

import datetime
import django.db.models.deletion
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_remove_inputlog_birthdate_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inputlog',
            name='description',
        ),
        migrations.RemoveField(
            model_name='inputlog',
            name='last_action',
        ),
        migrations.RemoveField(
            model_name='inputlog',
            name='last_action_date',
        ),
        migrations.RemoveField(
            model_name='inputlog',
            name='status',
        ),
        migrations.AlterField(
            model_name='inputlog',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Age'),
        ),
        migrations.AlterField(
            model_name='inputlog',
            name='city_of_residence',
            field=models.CharField(max_length=255, verbose_name='City of Residence'),
        ),
        migrations.AlterField(
            model_name='inputlog',
            name='drugs_cost',
            field=models.PositiveIntegerField(verbose_name='Drugs Cost'),
        ),
        migrations.AlterField(
            model_name='inputlog',
            name='province_of_residence',
            field=models.CharField(choices=[('alborz', 'Alborz'), ('ardabil', 'Ardabil'), ('bushehr', 'Bushehr'), ('chaharmahal_and_bakhtiari', 'Chaharmahal and Bakhtiari'), ('east_azerbaijan', 'East Azerbaijan'), ('isfahan', 'Isfahan'), ('fars', 'Fars'), ('gilan', 'Gilan'), ('golestan', 'Golestan'), ('hamadan', 'Hamadan'), ('hormozgan', 'Hormozgan'), ('ilam', 'Ilam'), ('kerman', 'Kerman'), ('kermanshah', 'Kermanshah'), ('khuzestan', 'Khuzestan'), ('kohgiluyeh_and_boyer_ahmad', 'Kohgiluyeh and Boyer-Ahmad'), ('kurdistan', 'Kurdistan'), ('lorestan', 'Lorestan'), ('markazi', 'Markazi'), ('mazandaran', 'Mazandaran'), ('north_khorasan', 'North Khorasan'), ('qazvin', 'Qazvin'), ('qom', 'Qom'), ('razavi_khorasan', 'Razavi Khorasan'), ('semnan', 'Semnan'), ('sistan_and_baluchestan', 'Sistan and Baluchestan'), ('south_khorasan', 'South Khorasan'), ('tehran', 'Tehran'), ('west_azerbaijan', 'West Azerbaijan'), ('yazd', 'Yazd'), ('zanjan', 'Zanjan'), ('not_iranian', 'Not Iranian')], max_length=30, verbose_name='Province of Residence'),
        ),
        migrations.AlterField(
            model_name='inputlog',
            name='referrer_name',
            field=models.CharField(max_length=255, verbose_name='Referrer Name'),
        ),
        migrations.AlterField(
            model_name='inputlog',
            name='service_date',
            field=django_jalali.db.models.jDateField(default=datetime.datetime.now, verbose_name='Service Date'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='InputLogHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('modified_at', models.DateField(auto_now=True, verbose_name='Modified At')),
                ('status', models.CharField(choices=[('reception', 'Reception'), ('waiting', 'Waiting'), ('rejection', 'Rejection'), ('detected', 'Detected'), ('reviewed', 'Reviewed')], max_length=30, verbose_name='Status')),
                ('last_action', models.TextField(blank=True, max_length=255, verbose_name='Last Action')),
                ('description', models.TextField(verbose_name='Description')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.inputlog', verbose_name='Patient')),
            ],
            options={
                'verbose_name': 'Input Log History',
                'verbose_name_plural': 'Input Log Histories',
            },
        ),
    ]
