# Generated by Django 5.0.3 on 2024-06-07 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientcase',
            name='active',
        ),
        migrations.RemoveField(
            model_name='patientcase',
            name='private_insurance_number',
        ),
        migrations.AddField(
            model_name='patientcase',
            name='private_insurance_description',
            field=models.TextField(blank=True, verbose_name='Private Insurance Description'),
        ),
        migrations.AddField(
            model_name='patientcase',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('waiting', 'Waiting'), ('semi-active', 'Semi Active')], default='waiting', max_length=20, verbose_name='Status'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patientcase',
            name='private_insurance_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Private Insurance Name'),
        ),
    ]
