# Generated by Django 5.0.3 on 2024-07-06 10:09

import django.db.models.deletion
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_remove_inputlog_birthdate_and_more'),
        ('patients', '0003_alter_document_uploaded_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='othersupporter',
            name='other_information',
        ),
        migrations.RemoveField(
            model_name='othersupporter',
            name='support_end',
        ),
        migrations.RemoveField(
            model_name='othersupporter',
            name='support_start',
        ),
        migrations.RemoveField(
            model_name='patientcase',
            name='amount_of_installment_or_debt',
        ),
        migrations.RemoveField(
            model_name='patientcase',
            name='city_of_residence',
        ),
        migrations.RemoveField(
            model_name='patientcase',
            name='deposit_amount',
        ),
        migrations.RemoveField(
            model_name='patientcase',
            name='family_monthly_expenses',
        ),
        migrations.RemoveField(
            model_name='patientcase',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='patientcase',
            name='has_job',
        ),
        migrations.RemoveField(
            model_name='patientcase',
            name='has_private_insurance',
        ),
        migrations.RemoveField(
            model_name='patientcase',
            name='helper_comment',
        ),
        migrations.RemoveField(
            model_name='patientcase',
            name='housing_status',
        ),
        migrations.RemoveField(
            model_name='patientcase',
            name='income_expenses_description',
        ),
        migrations.RemoveField(
            model_name='patientcase',
            name='job_description',
        ),
        migrations.RemoveField(
            model_name='patientcase',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='patientcase',
            name='mobile_number',
        ),
        migrations.RemoveField(
            model_name='patientcase',
            name='monthly_income',
        ),
        migrations.RemoveField(
            model_name='patientcase',
            name='patient_problem',
        ),
        migrations.RemoveField(
            model_name='patientcase',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='patientcase',
            name='province_of_residence',
        ),
        migrations.RemoveField(
            model_name='patientcase',
            name='refer_date',
        ),
        migrations.RemoveField(
            model_name='patientcase',
            name='referrer_name',
        ),
        migrations.RemoveField(
            model_name='patientcase',
            name='rent_amount',
        ),
        migrations.RemoveField(
            model_name='patientcase',
            name='repayment_due_date',
        ),
        migrations.RemoveField(
            model_name='patientcase',
            name='subsidy',
        ),
        migrations.AddField(
            model_name='othersupporter',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='othersupporter',
            name='is_active',
            field=models.BooleanField(null=True, verbose_name='Active'),
        ),
        migrations.AddField(
            model_name='othersupporter',
            name='support_count',
            field=models.IntegerField(default=0, verbose_name='Support Count'),
        ),
        migrations.AddField(
            model_name='patientcase',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='patientcase',
            name='home_number',
            field=models.CharField(default=1, max_length=20, verbose_name='Home Number'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patientcase',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.inputlog', verbose_name='Patient'),
        ),
        migrations.AddField(
            model_name='patientcase',
            name='representor_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Representor Phone'),
        ),
        migrations.AlterField(
            model_name='patientcase',
            name='case_number',
            field=models.CharField(max_length=255, verbose_name='Case Number'),
        ),
        migrations.AlterField(
            model_name='patientcase',
            name='first_guardian_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='First Guardian Name'),
        ),
        migrations.AlterField(
            model_name='patientcase',
            name='first_guardian_relation',
            field=models.CharField(blank=True, max_length=255, verbose_name='First Guardian Relation'),
        ),
        migrations.AlterField(
            model_name='patientcase',
            name='representor',
            field=models.CharField(blank=True, max_length=255, verbose_name='Representor'),
        ),
        migrations.AlterField(
            model_name='patientcase',
            name='representor_relation',
            field=models.CharField(blank=True, max_length=255, verbose_name='Representor Relation'),
        ),
        migrations.AlterField(
            model_name='patientcase',
            name='social_insurance_type',
            field=models.CharField(choices=[('health_insurance', 'Health Insurance'), ('social_security', 'Social Security'), ('villagers_and_nomads', 'Villagers and Nomads'), ('government_employees', 'Government Employees'), ('special_diseases', 'Special Diseases'), ('other_layers', 'Other Layers'), ('medical_services', 'Medical Services'), ('armed_forces', 'Armed Forces'), ('foreigners_social_security', 'Foreigners-Health'), ('foreigners_health', 'Foreigners-Social Security'), ('other', 'Other'), ('none', 'None'), ('foreigners_none', 'Foreigners-None'), ('baloch_none', 'Baloch-None')], max_length=255, verbose_name='Social Insurance Type'),
        ),
        migrations.AlterField(
            model_name='relative',
            name='health_status',
            field=models.TextField(blank=True, verbose_name='Health Status'),
        ),
        migrations.CreateModel(
            name='ApplicationSupport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Created At')),
                ('modified_at', models.DateField(auto_now=True, verbose_name='Modified At')),
                ('multiple_receive', models.BooleanField(null=True, verbose_name='Multiple Receive')),
                ('is_active', models.BooleanField(null=True, verbose_name='Active')),
                ('first_intake_date', django_jalali.db.models.jDateField(verbose_name='First Intake Date')),
                ('prescription_cost', models.IntegerField(verbose_name='Prescription Cost')),
                ('help_intervals', models.CharField(choices=[('two_weeks', 'Two Weeks'), ('three_weeks', 'Three Weeks'), ('monthly', 'Monthly'), ('two_months', 'Two_Months'), ('three_months', 'Three_Months'), ('six_months', 'Six_Months')], max_length=20, verbose_name='Help Intervals')),
                ('supplier_pharmacy', models.CharField(max_length=255, verbose_name='Supplier Pharmacy')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('patient_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patientcase', verbose_name='Patient Case')),
            ],
            options={
                'verbose_name': 'Application Support',
                'verbose_name_plural': 'Application Supports',
            },
        ),
        migrations.CreateModel(
            name='LivelihoodAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Created At')),
                ('modified_at', models.DateField(auto_now=True, verbose_name='Modified At')),
                ('housing_status', models.CharField(choices=[('owner', 'مالک'), ('rental', 'استیجاری- اجاره'), ('mortgaged', 'استیجاری - رهن'), ('mortgaged_rental', 'استیجاری - رهن و اجاره'), ('endowment', 'اوقاف'), ('relatives', 'بستگان'), ('janitor', 'سرایدار'), ('parents_house', 'Parents House'), ('child_house', 'Child House'), ('relative_house', 'Relative House'), ('other', 'Other')], max_length=20, verbose_name='Housing Status')),
                ('deposit_amount', models.IntegerField(default=0, verbose_name='Deposit Amount')),
                ('rent_amount', models.IntegerField(default=0, verbose_name='Rent Amount')),
                ('has_job', models.BooleanField(null=True, verbose_name='Has Job')),
                ('job_description', models.TextField(blank=True, verbose_name='Job Description')),
                ('monthly_income', models.IntegerField(verbose_name='Monthly Income')),
                ('other_monthly_income', models.IntegerField(default=0, verbose_name='Other Monthly Income')),
                ('subsidy', models.IntegerField(verbose_name='Subsidy')),
                ('family_monthly_expenses', models.IntegerField(verbose_name='Family Monthly Expenses')),
                ('amount_of_installment_or_debt', models.IntegerField(verbose_name='Amount of Installment or Debt')),
                ('repayment_due_date', django_jalali.db.models.jDateField(verbose_name='Repayment Due Date')),
                ('income_expenses_description', models.TextField(blank=True, verbose_name='Income Expenses Description')),
                ('recipient', models.CharField(choices=[('patient', 'Patient'), ('companion', 'Companion')], max_length=10, verbose_name='Recipient')),
                ('patient_problem', models.TextField(blank=True, verbose_name='Patient Problem')),
                ('helper_comment', models.TextField(blank=True, verbose_name='Helper Comment')),
                ('helper_assessment', models.TextField(blank=True, verbose_name='Helper Assessment')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('patient_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patientcase', verbose_name='Patient Case')),
            ],
            options={
                'verbose_name': 'Livelihood Assessment',
                'verbose_name_plural': 'Livelihood Assessments',
            },
        ),
        migrations.CreateModel(
            name='PatientHelperHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Created At')),
                ('modified_at', models.DateField(auto_now=True, verbose_name='Modified At')),
                ('patient_description', models.TextField(verbose_name='Patient Description')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('patient_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patientcase', verbose_name='Patient Case')),
            ],
            options={
                'verbose_name': 'Patient Helper History',
                'verbose_name_plural': 'Patient Helper Histories',
            },
        ),
        migrations.CreateModel(
            name='SupportProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Created At')),
                ('modified_at', models.DateField(auto_now=True, verbose_name='Modified At')),
                ('percentage', models.IntegerField(verbose_name='Percentage')),
                ('amount', models.IntegerField(verbose_name='Amount')),
                ('intervals', models.CharField(max_length=255, verbose_name='Intervals')),
                ('count', models.IntegerField(verbose_name='Count')),
                ('end_date', django_jalali.db.models.jDateField(verbose_name='End Date')),
                ('support_program', models.CharField(choices=[('one_time_payment', 'One Time Payment'), ('supervisor_approval', 'Supervisor Approval'), ('program', 'Program')], max_length=20, verbose_name='Support Program')),
                ('program_type', models.CharField(max_length=255, verbose_name='Program Type')),
                ('service_pharmacy', models.CharField(max_length=255, verbose_name='Service Pharmacy')),
                ('drug_delivery_type', models.CharField(choices=[('self', 'Self'), ('send', 'Send')], max_length=20, verbose_name='Drug Delivery Type')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], max_length=20, verbose_name='Status')),
                ('patient_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patientcase', verbose_name='Patient Case')),
            ],
            options={
                'verbose_name': 'Support Program',
                'verbose_name_plural': 'Support Programs',
            },
        ),
    ]
