# Generated by Django 5.0.3 on 2024-07-07 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drafts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='draft',
            name='receive_description',
            field=models.TextField(blank=True, default=None, verbose_name='Receive Description'),
        ),
        migrations.AddField(
            model_name='draft',
            name='receive_status',
            field=models.CharField(choices=[('received', 'دریافت شده'), ('pending', 'در انتظار'), ('not-received', 'دریافت نشده')], default='pending', max_length=20, verbose_name='Receive Status'),
        ),
    ]
