# Generated by Django 5.0.3 on 2024-07-09 20:16

import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drafts', '0002_draft_receive_description_draft_receive_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='draft',
            name='cash_draft_amount',
        ),
        migrations.RemoveField(
            model_name='draft',
            name='draft_create_date',
        ),
        migrations.RemoveField(
            model_name='draft',
            name='drug_draft_amount',
        ),
        migrations.RemoveField(
            model_name='draft',
            name='supplier_name',
        ),
        migrations.RemoveField(
            model_name='draft',
            name='supplier_type',
        ),
        migrations.AddField(
            model_name='draft',
            name='cash_amount',
            field=models.FloatField(default=0, verbose_name='Cash Amount'),
        ),
        migrations.AddField(
            model_name='draft',
            name='description',
            field=models.TextField(blank=True, default=None, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='draft',
            name='draft_caused',
            field=models.CharField(choices=[('drug', 'دارو'), ('test', 'آزمایش'), ('imaging', 'عکسبرداری'), ('discharge', 'ترخیص')], default='drug', max_length=30, verbose_name='Draft Caused'),
        ),
        migrations.AddField(
            model_name='draft',
            name='draft_receiver',
            field=models.CharField(choices=[('pharmacy', 'داروخانه'), ('individual', 'شخص'), ('factory', 'کارخانه'), ('medical-center', 'مرکز درمانی')], default='pharmacy', max_length=30, verbose_name='Draft Receiver'),
        ),
        migrations.AddField(
            model_name='draft',
            name='franchise',
            field=models.FloatField(default=0, verbose_name='Franchise'),
        ),
        migrations.AddField(
            model_name='draft',
            name='medicine_amount',
            field=models.FloatField(default=0, verbose_name='Medicine Amount'),
        ),
        migrations.AddField(
            model_name='draft',
            name='modify_description',
            field=models.TextField(blank=True, default=None, verbose_name='Modify Description'),
        ),
        migrations.AddField(
            model_name='draft',
            name='next_visit',
            field=django_jalali.db.models.jDateField(default=None, verbose_name='Next Visit'),
        ),
        migrations.AddField(
            model_name='draft',
            name='receiving_center',
            field=models.CharField(default='', max_length=200, verbose_name='Receiving Center'),
        ),
        migrations.AddField(
            model_name='draft',
            name='support_type',
            field=models.CharField(choices=[('cash', 'نقدی'), ('non-cash', 'غیر نقدی'), ('mix', 'هردو')], default='mix', max_length=10, verbose_name='Support Type'),
        ),
        migrations.AddField(
            model_name='draft',
            name='total_amount',
            field=models.FloatField(default=0, verbose_name='Total Amount'),
        ),
        migrations.AddField(
            model_name='draftdrug',
            name='dose',
            field=models.CharField(default='', max_length=256, verbose_name='Dose'),
        ),
        migrations.AddField(
            model_name='draftdrug',
            name='duration',
            field=models.PositiveIntegerField(default=0, verbose_name='Duration(Day)'),
        ),
        migrations.AddField(
            model_name='draftdrug',
            name='start_date',
            field=django_jalali.db.models.jDateField(default=None, verbose_name='Start Taking Date'),
        ),
        migrations.AddField(
            model_name='draftdrug',
            name='unit_price',
            field=models.PositiveIntegerField(default=0, verbose_name='Unit Price'),
        ),
        migrations.AlterField(
            model_name='draft',
            name='draft_type',
            field=models.CharField(choices=[('P', 'حواله کاغذی'), ('IT', 'حواله اینترنتی'), ('F', 'فاکتور'), ('DM', 'اعتباری دارو'), ('DD', 'اعتباری تخفیف')], max_length=10, verbose_name='Draft Type'),
        ),
        migrations.AlterField(
            model_name='draft',
            name='insurance_amount',
            field=models.FloatField(default=0, verbose_name='Insurance Amount'),
        ),
        migrations.AlterField(
            model_name='draft',
            name='patient_amount',
            field=models.FloatField(default=0, verbose_name='Patient Amount'),
        ),
        migrations.AlterField(
            model_name='draft',
            name='receive_status',
            field=models.CharField(choices=[('pending', 'در انتظار'), ('received', 'دریافت شده'), ('not-received', 'دریافت نشده')], default='pending', max_length=20, verbose_name='Receive Status'),
        ),
        migrations.AlterField(
            model_name='draft',
            name='status',
            field=models.CharField(choices=[('accepted', 'تایید'), ('voided', 'باطل'), ('modify-amount', 'اصلاح مبلغ')], max_length=30, verbose_name='Status'),
        ),
    ]
